### ISSUE TITLE
Encoding library

### ISSUE THREAD

**Issue by justinbass** [piql/unboxing#2]
This library is great for showing off the general scheme of the Piql data matrix, but the test data included is limited. Are there any future plans to include an encoding library that can take in a file and create a Piql data matrix image8 file, to test decoding? It looks like a majority of the code infrastructure is in place to do so.

There have also been many other small similar projects (Paperbak, Optar, Colorsafe) to attempt printing in this way for personal use on paper, while Piql's data matrix is by far the most advanced. This can be useful for printing small amounts of data on paper, though ink is expensive and limited unlike the Piql film reel's multi-gigabyte capacity.

**Comment by oleliabo** [comment]
Hello, yes it's a limitation of the open-source version of the library that the public API for encoding data is left out. We hope to include this in the future, including the full format description etc. 

We have tested encoding / decoding from paper, and it works well.

**Comment by RokerHRO** [comment]
This comment is >4 years old, so I think the company behind this format is unable or unwilling to open their format completely. :-(
So I'll stay with QR codes which work absolutely fine. And there are lots of free encoding and decoding libraries out there. (and a free and open format specification, enabling you to write your own library, too.)

**Comment by justinbass** [comment]
That is correct. I reached out to PIQL by e-mail recently (in the last year) and they mentioned they are unwilling to share their encoder code. Thus while it is an open ISO standard, it's not free - you'd have to pay $ to buy the ISO standard, and there is no source code. So it's not free or open source. I do not advise it. I have been using https://github.com/colindean/optar for personal use.

I also was working on https://github.com/makocodeproject/makocode but it's just a draft of a standard currently.

To be fair, an old quote for PIQL film from their team indicated that it's probably an order of magnitude cheaper for large amounts of data compared to Optar on my laser printer (they quoted me for 40 GB, I won't share the price due to NDA). So they are good if you want to encode lots of data. For small amounts (<1 GB), maybe just use optar.

**Comment by justinbass** [comment]
Won't fix, as per e-mail correspondence.
